MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    HEAD_NAME: "ThunderNetRPNHead"
    IN_FEATURES: ["rpn_in_features"]
  PROPOSAL_GENERATOR:
    NAME: "ThunderNetRPN"
  ROI_HEADS:
    NAME: "ThunderNetROIHeads"
    IN_FEATURES: ["sam"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    POOLER_RESOLUTION: 7
    NUM_FC: 1
    FC_DIM: 1024
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (320, )
  MIN_SIZE_TEST: 800
  CROP:
    ENABLED: true
    TYPE: absolute
    SIZE: [320, 320]
