MODEL:
  META_ARCHITECTURE: "ThunderNet"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    HEAD_NAME: "ThunderNetRPNHead"
    IN_FEATURES: ["cem"]
  PROPOSAL_GENERATOR:
    NAME: "ThunderNetRPN"
  ROI_HEADS:
    NAME: "ThunderNetROIHeads"
    IN_FEATURES: ["cem_rpn_features"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    POOLER_RESOLUTION: 7
  BACKBONE:
    NAME: "SNet"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
